"""Stable STT provider contract used by Maya."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class AudioDevice:
    name: str
    description: str


class STTCallbacks(Protocol):
    def started(self) -> None: ...
    def transcribing(self) -> None: ...
    def transcript(self, text: str) -> None: ...
    def failed(self, message: str) -> None: ...
    def level(self, value: float) -> None: ...


class STTProvider(Protocol):
    name: str

    def list_devices(self) -> list[AudioDevice]: ...
    def start(self, device: str, language: str, model: str, callbacks: STTCallbacks) -> None: ...
    def stop(self) -> None: ...
    def cancel(self) -> None: ...
    def transcribe_file(self, path: str, language: str, model: str, callbacks: STTCallbacks) -> None: ...
