"""Stable wake provider callbacks."""

from __future__ import annotations

from typing import Protocol


class WakeCallbacks(Protocol):
    def detected(self) -> None: ...
    def command_ready(self, path: str) -> None: ...
    def failed(self, message: str) -> None: ...
    def level(self, value: float) -> None: ...


class WakeProvider(Protocol):
    name: str

    def start(self, sensitivity: float, callbacks: WakeCallbacks) -> None: ...
    def stop(self, reason: str = "requested") -> None: ...
    def pause(self, reason: str = "requested") -> bool: ...
    def resume(self) -> bool: ...
    def release_command(self, path: str) -> None: ...
